## Numpy Manual

In [2]:
import numpy as np

### 배열생성

numpy 자료형

- i - integer (정수)
- ? - boolean (참거짓)
- u - unsigned integer (부호없는 정수)
- f - float (소수)
- c - complex (복소수)
- m - timedelta (타임델타)
- M - datetime (날짜시간)
- O - object (객체)
- S - string (문자열)
- U - unicode string (유니코드 문자열)
- V - void (다른 유형에 대한 고정된 메모리 덩어리)

예시
```python
i1 # 1바이트(8비트) 정수
```

ndarray 속성
```python
a = np.arnage(15).reshape(3, 5)
print(a.ndim)
ndim # 차원수
itemsize # 아이템 별 크기
size # 아이템 개수
nbytes # 배열의 총 크기 = 아이템 개수 * 아이템 크기
T # 교차된 배열
shape # 배열의 모양
flat
imag
real
```

In [3]:
# 배열생성
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros(5, dtype=np.int)

C:\Users\csjty\AppData\Local\Temp\ipykernel_40020\3151184454.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.zeros(5, dtype=np.int)


array([0, 0, 0, 0, 0])

In [14]:
np.zeros((2, 1))

array([[0.],
       [0.]])

In [15]:
# custom dtype
np.zeros((2,), dtype=[('x', 'i4'), ('y', 'i4')])

array([(0, 0), (0, 0)], dtype=[('x', '<i4'), ('y', '<i4')])

In [3]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [4]:
np.array([0, 1, 2, 3, 4, 5])

array([0, 1, 2, 3, 4, 5])

In [5]:
m = np.array([np.arange(2), np.arange(2)])
m

array([[0, 1],
       [0, 1]])

In [6]:
m.shape

(2, 2)

In [12]:
# 초기화 배열
np.empty([2, 2], dtype=int)

array([[        0,         0],
       [538781136,       613]])

In [20]:
# 랜덤 배열 생성
# 정규화 분산 데이터로부터 랜덤한 값 리턴
np.random.randn(2, 4)

# np.random.randint(n1, n2) n1~n2 사이의 정수 생성
np.random.randint(3, 8, size=10)

array([5, 7, 6, 5, 5, 5, 3, 7, 6, 4])

In [23]:
# 형 선언하기
arr1 = np.array([1, 2, 3], dtype='float')
arr2 = np.array([1, 2, 3], dtype='int32')
print(arr1.dtype)
print(arr2.dtype)
arr1 = np.array([1.5, 2.1, 1.3], dtype='float')
arr2 = arr1.astype(np.int32)
print(arr2)

float64
int32
[1 2 1]


In [29]:
a = np.arange(15).reshape(3, 5)
print(a)
print('---------일반 속성---------')
print(f'차원수 : {a.ndim}')
print(f'아이템 별 크기: {a.itemsize}')
print(f'아이템 개수 : {a.size}')
print(f'배열의 총 크기 = 아이템 개수 * 아이템 크기 : {a.nbytes}')
print(f'교차된 배열 : {a.T}')
print(f'배열의 모양 : {a.shape}')
print('---------복소수 속성---------')
print(f'flat : {a.flat}')
print(f'imag : {a.imag}')
print(f'real : {a.real}')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
---------일반 속성---------
차원수 : 2
아이템 별 크기: 4
아이템 개수 : 15
배열의 총 크기 = 아이템 개수 * 아이템 크기 : 60
교차된 배열 : [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
배열의 모양 : (3, 5)
---------복소수 속성---------
flat : <numpy.flatiter object at 0x000002651F0A7460>
imag : [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
real : [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [30]:
a.dtype.name

'int32'

### 배열 인덱싱

In [8]:
m[0, 1] = 3
m

array([[0, 3],
       [0, 1]])

In [9]:
# 배열연산
m + 2

array([[2, 5],
       [2, 3]])

In [10]:
m[0, 1:]

array([3])

## 배열 모양 조작
- ravel: 1차원으로 변경
- faltten: 1차원으로 변경, 새로운 메모리에 저장됨
- shape: 튜플을 수정해 정의, 해당 변수 메로리 직접 변조
- Transpose(): 교차시킴, 행은 열이 되고 열은 행이 됨
- Resize(a, b): 배열을 원하는 모양으로 바꿈, reshape은 출력을 변경하지만, resize는 배열을 직접 바꾼다.

In [44]:
b = np.arange(24)
print(f'{b}\n')

b.ravel()
print(f'b.ravel(): {b}\n')

b.shape = (6, 4)
print(f'shape = (6, 4): {b}\n')

b.transpose()
print(f'b.transpose(): {b}\n')

print(f'b.flatten(): {b.flatten()}\n')

b.resize()
print(f'b.resize(): {b}\n')

b.resize((2, 12))
print(f'b.resize((2, 12)): {b}\n')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

b.ravel(): [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

shape = (6, 4): [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

b.transpose(): [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

b.flatten(): [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

b.resize(): [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

b.resize((2, 12)): [[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]



## Reference
- [ml-ko.kr](https://ml-ko.kr/homl2/tools_numpy.html)